/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false --strict-vars=false` (hash: 5947b7943b631faf5025650883c4b335)
interface __BaseEnv_Env {
	DB: D1Database;
	ASSETS: Fetcher;
	AUTH_USERNAME: string;
	AUTH_PASSWORD_PARAMETERS: string;
	AUTH_PASSWORD_VERIFIER: string;
	AUTH_PEPPER: string;
	AUTH_TOTP_SECRET: string;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./worker/index");
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "AUTH_USERNAME" | "AUTH_PASSWORD_PARAMETERS" | "AUTH_PASSWORD_VERIFIER" | "AUTH_PEPPER" | "AUTH_TOTP_SECRET">> {}
}
